name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
  schedule:
  - cron: '00 01 * * *'
jobs:
  build:
    name: build

    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
      CARGO_INCREMENTAL: 0

    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        rust_version:
          - nightly

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust_version }}-x86_64-pc-windows-gnu
        target: x86_64-pc-windows-gnu
        profile: minimal
        override: true

    - name: Provide environment information
      shell: bash
      run: |
        rustc --version --verbose
        which gcc.exe
        which x86_64-w64-mingw32-gcc.exe
        which bash.exe
        gcc.exe --version
        x86_64-w64-mingw32-gcc.exe --version

    - name: Build
      shell: bash
      run: cargo build --verbose --target x86_64-pc-windows-gnu
